// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package filedownloadmanager

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Filename struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Filename) Reset()         { *m = Filename{} }
func (m *Filename) String() string { return proto.CompactTextString(m) }
func (*Filename) ProtoMessage()    {}
func (*Filename) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Filename) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filename.Unmarshal(m, b)
}
func (m *Filename) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filename.Marshal(b, m, deterministic)
}
func (m *Filename) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filename.Merge(m, src)
}
func (m *Filename) XXX_Size() int {
	return xxx_messageInfo_Filename.Size(m)
}
func (m *Filename) XXX_DiscardUnknown() {
	xxx_messageInfo_Filename.DiscardUnknown(m)
}

var xxx_messageInfo_Filename proto.InternalMessageInfo

func (m *Filename) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type File struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*Filename)(nil), "filedownloadmanager.filename")
	proto.RegisterType((*File)(nil), "filedownloadmanager.file")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x4e, 0xcb, 0xcc, 0x49, 0x4d,
	0xc9, 0x2f, 0xcf, 0xcb, 0xc9, 0x4f, 0x4c, 0xc9, 0x4d, 0xcc, 0x4b, 0x4c, 0x4f, 0x2d, 0x52, 0x92,
	0xe3, 0xe2, 0x00, 0x09, 0xe7, 0x25, 0xe6, 0xa6, 0x0a, 0x09, 0x71, 0xb1, 0x80, 0x68, 0x09, 0x46,
	0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x5b, 0x49, 0x81, 0x8b, 0x05, 0x24, 0x2f, 0x24, 0xc1, 0xc5,
	0x9e, 0x9c, 0x9f, 0x57, 0x92, 0x9a, 0x57, 0x02, 0x96, 0xe6, 0x09, 0x82, 0x71, 0x8d, 0xa2, 0xb8,
	0xb0, 0x19, 0x2c, 0xe4, 0xcc, 0xc5, 0x9e, 0x9e, 0x5a, 0xe2, 0x06, 0xd2, 0x2b, 0xab, 0x87, 0x45,
	0x81, 0x1e, 0xcc, 0x5a, 0x29, 0x49, 0x9c, 0xd2, 0x4e, 0xa2, 0x51, 0xd8, 0xcc, 0x4e, 0x62, 0x03,
	0x7b, 0xc8, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xef, 0xb5, 0x2a, 0x46, 0xe1, 0x00, 0x00, 0x00,
}
